on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    name: Build and publish nebius-connect package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/nebius-connect
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up build environment
        run: pipx install build
      - name: Build package distributions
        run: pipx run build
      - name: Publish package distributions to PyPI
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@release/v1
